// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.29.3
// source: strategy/models/account.proto

package strategy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBiconomyAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAddress string `protobuf:"bytes,1,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
}

func (x *GetBiconomyAccountRequest) Reset() {
	*x = GetBiconomyAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBiconomyAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBiconomyAccountRequest) ProtoMessage() {}

func (x *GetBiconomyAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBiconomyAccountRequest.ProtoReflect.Descriptor instead.
func (*GetBiconomyAccountRequest) Descriptor() ([]byte, []int) {
	return file_strategy_models_account_proto_rawDescGZIP(), []int{0}
}

func (x *GetBiconomyAccountRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

type BiconomyAccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAddress         string `protobuf:"bytes,1,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
	OrchestratorAddress string `protobuf:"bytes,2,opt,name=orchestratorAddress,proto3" json:"orchestratorAddress,omitempty"`
	ChainId             int64  `protobuf:"varint,3,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Index               int32  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	StrategyId          string `protobuf:"bytes,5,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
}

func (x *BiconomyAccountInfo) Reset() {
	*x = BiconomyAccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BiconomyAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BiconomyAccountInfo) ProtoMessage() {}

func (x *BiconomyAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BiconomyAccountInfo.ProtoReflect.Descriptor instead.
func (*BiconomyAccountInfo) Descriptor() ([]byte, []int) {
	return file_strategy_models_account_proto_rawDescGZIP(), []int{1}
}

func (x *BiconomyAccountInfo) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *BiconomyAccountInfo) GetOrchestratorAddress() string {
	if x != nil {
		return x.OrchestratorAddress
	}
	return ""
}

func (x *BiconomyAccountInfo) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *BiconomyAccountInfo) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *BiconomyAccountInfo) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

type GetBiconomyAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data []*BiconomyAccountInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetBiconomyAccountResponse) Reset() {
	*x = GetBiconomyAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_account_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBiconomyAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBiconomyAccountResponse) ProtoMessage() {}

func (x *GetBiconomyAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_account_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBiconomyAccountResponse.ProtoReflect.Descriptor instead.
func (*GetBiconomyAccountResponse) Descriptor() ([]byte, []int) {
	return file_strategy_models_account_proto_rawDescGZIP(), []int{2}
}

func (x *GetBiconomyAccountResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetBiconomyAccountResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetBiconomyAccountResponse) GetData() []*BiconomyAccountInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_strategy_models_account_proto protoreflect.FileDescriptor

var file_strategy_models_account_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x08, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x22, 0x3d, 0x0a, 0x19, 0x47, 0x65, 0x74,
	0x42, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xb9, 0x01, 0x0a, 0x13, 0x42, 0x69, 0x63,
	0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x20, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x30, 0x0a, 0x13, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x13, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69,
	0x6e, 0x64, 0x65, 0x78, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79,
	0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x49, 0x64, 0x22, 0x75, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x42, 0x69, 0x63, 0x6f, 0x6e,
	0x6f, 0x6d, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x31, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67,
	0x79, 0x2e, 0x42, 0x69, 0x63, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x19, 0x5a, 0x17, 0x70,
	0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x3b, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_strategy_models_account_proto_rawDescOnce sync.Once
	file_strategy_models_account_proto_rawDescData = file_strategy_models_account_proto_rawDesc
)

func file_strategy_models_account_proto_rawDescGZIP() []byte {
	file_strategy_models_account_proto_rawDescOnce.Do(func() {
		file_strategy_models_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_strategy_models_account_proto_rawDescData)
	})
	return file_strategy_models_account_proto_rawDescData
}

var file_strategy_models_account_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_strategy_models_account_proto_goTypes = []interface{}{
	(*GetBiconomyAccountRequest)(nil),  // 0: strategy.GetBiconomyAccountRequest
	(*BiconomyAccountInfo)(nil),        // 1: strategy.BiconomyAccountInfo
	(*GetBiconomyAccountResponse)(nil), // 2: strategy.GetBiconomyAccountResponse
}
var file_strategy_models_account_proto_depIdxs = []int32{
	1, // 0: strategy.GetBiconomyAccountResponse.data:type_name -> strategy.BiconomyAccountInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_strategy_models_account_proto_init() }
func file_strategy_models_account_proto_init() {
	if File_strategy_models_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_strategy_models_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBiconomyAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BiconomyAccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_account_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBiconomyAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_strategy_models_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_strategy_models_account_proto_goTypes,
		DependencyIndexes: file_strategy_models_account_proto_depIdxs,
		MessageInfos:      file_strategy_models_account_proto_msgTypes,
	}.Build()
	File_strategy_models_account_proto = out.File
	file_strategy_models_account_proto_rawDesc = nil
	file_strategy_models_account_proto_goTypes = nil
	file_strategy_models_account_proto_depIdxs = nil
}
