// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.29.3
// source: strategy/models/apy.proto

package strategy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAPYRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrategyId string `protobuf:"bytes,1,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	Amount     string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *GetAPYRequest) Reset() {
	*x = GetAPYRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_apy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAPYRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPYRequest) ProtoMessage() {}

func (x *GetAPYRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_apy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPYRequest.ProtoReflect.Descriptor instead.
func (*GetAPYRequest) Descriptor() ([]byte, []int) {
	return file_strategy_models_apy_proto_rawDescGZIP(), []int{0}
}

func (x *GetAPYRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *GetAPYRequest) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type APYInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	YieldAmount      string `protobuf:"bytes,1,opt,name=yieldAmount,proto3" json:"yieldAmount,omitempty"`
	BorrowFeeAmount  string `protobuf:"bytes,2,opt,name=borrowFeeAmount,proto3" json:"borrowFeeAmount,omitempty"`
	FinalYieldAmount string `protobuf:"bytes,3,opt,name=finalYieldAmount,proto3" json:"finalYieldAmount,omitempty"`
	InputAmount      string `protobuf:"bytes,4,opt,name=inputAmount,proto3" json:"inputAmount,omitempty"`
}

func (x *APYInfo) Reset() {
	*x = APYInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_apy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APYInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APYInfo) ProtoMessage() {}

func (x *APYInfo) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_apy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APYInfo.ProtoReflect.Descriptor instead.
func (*APYInfo) Descriptor() ([]byte, []int) {
	return file_strategy_models_apy_proto_rawDescGZIP(), []int{1}
}

func (x *APYInfo) GetYieldAmount() string {
	if x != nil {
		return x.YieldAmount
	}
	return ""
}

func (x *APYInfo) GetBorrowFeeAmount() string {
	if x != nil {
		return x.BorrowFeeAmount
	}
	return ""
}

func (x *APYInfo) GetFinalYieldAmount() string {
	if x != nil {
		return x.FinalYieldAmount
	}
	return ""
}

func (x *APYInfo) GetInputAmount() string {
	if x != nil {
		return x.InputAmount
	}
	return ""
}

type GetAPYResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *APYInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAPYResponse) Reset() {
	*x = GetAPYResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_apy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAPYResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAPYResponse) ProtoMessage() {}

func (x *GetAPYResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_apy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAPYResponse.ProtoReflect.Descriptor instead.
func (*GetAPYResponse) Descriptor() ([]byte, []int) {
	return file_strategy_models_apy_proto_rawDescGZIP(), []int{2}
}

func (x *GetAPYResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAPYResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetAPYResponse) GetData() *APYInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_strategy_models_apy_proto protoreflect.FileDescriptor

var file_strategy_models_apy_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x61, 0x70, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x22, 0x47, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x50, 0x59, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0xa3,
	0x01, 0x0a, 0x07, 0x41, 0x50, 0x59, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x79, 0x69,
	0x65, 0x6c, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x79, 0x69, 0x65, 0x6c, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x0a, 0x0f,
	0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x46, 0x65, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x62, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x46, 0x65, 0x65,
	0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x2a, 0x0a, 0x10, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x59,
	0x69, 0x65, 0x6c, 0x64, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x59, 0x69, 0x65, 0x6c, 0x64, 0x41, 0x6d, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x41, 0x6d,
	0x6f, 0x75, 0x6e, 0x74, 0x22, 0x5d, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x50, 0x59, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x25, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x2e, 0x41, 0x50, 0x59, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x42, 0x19, 0x5a, 0x17, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x3b, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_strategy_models_apy_proto_rawDescOnce sync.Once
	file_strategy_models_apy_proto_rawDescData = file_strategy_models_apy_proto_rawDesc
)

func file_strategy_models_apy_proto_rawDescGZIP() []byte {
	file_strategy_models_apy_proto_rawDescOnce.Do(func() {
		file_strategy_models_apy_proto_rawDescData = protoimpl.X.CompressGZIP(file_strategy_models_apy_proto_rawDescData)
	})
	return file_strategy_models_apy_proto_rawDescData
}

var file_strategy_models_apy_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_strategy_models_apy_proto_goTypes = []interface{}{
	(*GetAPYRequest)(nil),  // 0: strategy.GetAPYRequest
	(*APYInfo)(nil),        // 1: strategy.APYInfo
	(*GetAPYResponse)(nil), // 2: strategy.GetAPYResponse
}
var file_strategy_models_apy_proto_depIdxs = []int32{
	1, // 0: strategy.GetAPYResponse.data:type_name -> strategy.APYInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_strategy_models_apy_proto_init() }
func file_strategy_models_apy_proto_init() {
	if File_strategy_models_apy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_strategy_models_apy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAPYRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_apy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APYInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_apy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAPYResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_strategy_models_apy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_strategy_models_apy_proto_goTypes,
		DependencyIndexes: file_strategy_models_apy_proto_depIdxs,
		MessageInfos:      file_strategy_models_apy_proto_msgTypes,
	}.Build()
	File_strategy_models_apy_proto = out.File
	file_strategy_models_apy_proto_rawDesc = nil
	file_strategy_models_apy_proto_goTypes = nil
	file_strategy_models_apy_proto_depIdxs = nil
}
