// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.29.3
// source: strategy/models/jobs.proto

package strategy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserJobsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAddress string `protobuf:"bytes,1,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
}

func (x *GetUserJobsRequest) Reset() {
	*x = GetUserJobsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_jobs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserJobsRequest) ProtoMessage() {}

func (x *GetUserJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_jobs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserJobsRequest.ProtoReflect.Descriptor instead.
func (*GetUserJobsRequest) Descriptor() ([]byte, []int) {
	return file_strategy_models_jobs_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserJobsRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

type UserJobInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId       string `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	CurrentStep int32  `protobuf:"varint,2,opt,name=currentStep,proto3" json:"currentStep,omitempty"`
	TotalSteps  int32  `protobuf:"varint,3,opt,name=totalSteps,proto3" json:"totalSteps,omitempty"`
	StrategyId  string `protobuf:"bytes,4,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	Action      string `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *UserJobInfo) Reset() {
	*x = UserJobInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_jobs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserJobInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserJobInfo) ProtoMessage() {}

func (x *UserJobInfo) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_jobs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserJobInfo.ProtoReflect.Descriptor instead.
func (*UserJobInfo) Descriptor() ([]byte, []int) {
	return file_strategy_models_jobs_proto_rawDescGZIP(), []int{1}
}

func (x *UserJobInfo) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *UserJobInfo) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *UserJobInfo) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *UserJobInfo) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *UserJobInfo) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type GetUserJobsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string         `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data []*UserJobInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetUserJobsResponse) Reset() {
	*x = GetUserJobsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_jobs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserJobsResponse) ProtoMessage() {}

func (x *GetUserJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_jobs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserJobsResponse.ProtoReflect.Descriptor instead.
func (*GetUserJobsResponse) Descriptor() ([]byte, []int) {
	return file_strategy_models_jobs_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserJobsResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserJobsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUserJobsResponse) GetData() []*UserJobInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetCurrentStepRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JobId string `protobuf:"bytes,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
}

func (x *GetCurrentStepRequest) Reset() {
	*x = GetCurrentStepRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_jobs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentStepRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentStepRequest) ProtoMessage() {}

func (x *GetCurrentStepRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_jobs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentStepRequest.ProtoReflect.Descriptor instead.
func (*GetCurrentStepRequest) Descriptor() ([]byte, []int) {
	return file_strategy_models_jobs_proto_rawDescGZIP(), []int{3}
}

func (x *GetCurrentStepRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type CurrentStepInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurrentStep int32  `protobuf:"varint,1,opt,name=currentStep,proto3" json:"currentStep,omitempty"`
	StepName    string `protobuf:"bytes,2,opt,name=stepName,proto3" json:"stepName,omitempty"`
	TotalSteps  int32  `protobuf:"varint,3,opt,name=totalSteps,proto3" json:"totalSteps,omitempty"`
	StrategyId  string `protobuf:"bytes,4,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	Type        string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *CurrentStepInfo) Reset() {
	*x = CurrentStepInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_jobs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CurrentStepInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrentStepInfo) ProtoMessage() {}

func (x *CurrentStepInfo) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_jobs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrentStepInfo.ProtoReflect.Descriptor instead.
func (*CurrentStepInfo) Descriptor() ([]byte, []int) {
	return file_strategy_models_jobs_proto_rawDescGZIP(), []int{4}
}

func (x *CurrentStepInfo) GetCurrentStep() int32 {
	if x != nil {
		return x.CurrentStep
	}
	return 0
}

func (x *CurrentStepInfo) GetStepName() string {
	if x != nil {
		return x.StepName
	}
	return ""
}

func (x *CurrentStepInfo) GetTotalSteps() int32 {
	if x != nil {
		return x.TotalSteps
	}
	return 0
}

func (x *CurrentStepInfo) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *CurrentStepInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetCurrentStepResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string           `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *CurrentStepInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetCurrentStepResponse) Reset() {
	*x = GetCurrentStepResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_jobs_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCurrentStepResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrentStepResponse) ProtoMessage() {}

func (x *GetCurrentStepResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_jobs_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrentStepResponse.ProtoReflect.Descriptor instead.
func (*GetCurrentStepResponse) Descriptor() ([]byte, []int) {
	return file_strategy_models_jobs_proto_rawDescGZIP(), []int{5}
}

func (x *GetCurrentStepResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCurrentStepResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetCurrentStepResponse) GetData() *CurrentStepInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_strategy_models_jobs_proto protoreflect.FileDescriptor

var file_strategy_models_jobs_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x6a, 0x6f, 0x62, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x22, 0x36, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b,
	0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x9d,
	0x01, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x14,
	0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a,
	0x6f, 0x62, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53,
	0x74, 0x65, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x63, 0x75, 0x72, 0x72, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x65, 0x70, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x53,
	0x74, 0x65, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61,
	0x6c, 0x53, 0x74, 0x65, 0x70, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65,
	0x67, 0x79, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x66,
	0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x29, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x4a, 0x6f, 0x62, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2d, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x6a, 0x6f, 0x62, 0x49, 0x64, 0x22, 0xa3, 0x01, 0x0a, 0x0f, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x74, 0x53, 0x74, 0x65, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x65, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b,
	0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x65, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x73,
	0x74, 0x65, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73,
	0x74, 0x65, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x53, 0x74, 0x65, 0x70, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x53, 0x74, 0x65, 0x70, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x65, 0x67, 0x79, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22, 0x6d, 0x0a, 0x16, 0x47,
	0x65, 0x74, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x65, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2d, 0x0a, 0x04, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x2e, 0x43, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x74, 0x65, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x19, 0x5a, 0x17, 0x70, 0x62,
	0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x3b, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_strategy_models_jobs_proto_rawDescOnce sync.Once
	file_strategy_models_jobs_proto_rawDescData = file_strategy_models_jobs_proto_rawDesc
)

func file_strategy_models_jobs_proto_rawDescGZIP() []byte {
	file_strategy_models_jobs_proto_rawDescOnce.Do(func() {
		file_strategy_models_jobs_proto_rawDescData = protoimpl.X.CompressGZIP(file_strategy_models_jobs_proto_rawDescData)
	})
	return file_strategy_models_jobs_proto_rawDescData
}

var file_strategy_models_jobs_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_strategy_models_jobs_proto_goTypes = []interface{}{
	(*GetUserJobsRequest)(nil),     // 0: strategy.GetUserJobsRequest
	(*UserJobInfo)(nil),            // 1: strategy.UserJobInfo
	(*GetUserJobsResponse)(nil),    // 2: strategy.GetUserJobsResponse
	(*GetCurrentStepRequest)(nil),  // 3: strategy.GetCurrentStepRequest
	(*CurrentStepInfo)(nil),        // 4: strategy.CurrentStepInfo
	(*GetCurrentStepResponse)(nil), // 5: strategy.GetCurrentStepResponse
}
var file_strategy_models_jobs_proto_depIdxs = []int32{
	1, // 0: strategy.GetUserJobsResponse.data:type_name -> strategy.UserJobInfo
	4, // 1: strategy.GetCurrentStepResponse.data:type_name -> strategy.CurrentStepInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_strategy_models_jobs_proto_init() }
func file_strategy_models_jobs_proto_init() {
	if File_strategy_models_jobs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_strategy_models_jobs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserJobsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_jobs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserJobInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_jobs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserJobsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_jobs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentStepRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_jobs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CurrentStepInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_jobs_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCurrentStepResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_strategy_models_jobs_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_strategy_models_jobs_proto_goTypes,
		DependencyIndexes: file_strategy_models_jobs_proto_depIdxs,
		MessageInfos:      file_strategy_models_jobs_proto_msgTypes,
	}.Build()
	File_strategy_models_jobs_proto = out.File
	file_strategy_models_jobs_proto_rawDesc = nil
	file_strategy_models_jobs_proto_goTypes = nil
	file_strategy_models_jobs_proto_depIdxs = nil
}
