// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.29.3
// source: strategy/models/strategy.proto

package strategy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetStrategyListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetStrategyListRequest) Reset() {
	*x = GetStrategyListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_strategy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStrategyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategyListRequest) ProtoMessage() {}

func (x *GetStrategyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_strategy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyListRequest.ProtoReflect.Descriptor instead.
func (*GetStrategyListRequest) Descriptor() ([]byte, []int) {
	return file_strategy_models_strategy_proto_rawDescGZIP(), []int{0}
}

type FeeToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	ChainId string `protobuf:"bytes,2,opt,name=chainId,proto3" json:"chainId,omitempty"`
}

func (x *FeeToken) Reset() {
	*x = FeeToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_strategy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeeToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeeToken) ProtoMessage() {}

func (x *FeeToken) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_strategy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeeToken.ProtoReflect.Descriptor instead.
func (*FeeToken) Descriptor() ([]byte, []int) {
	return file_strategy_models_strategy_proto_rawDescGZIP(), []int{1}
}

func (x *FeeToken) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *FeeToken) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

type StrategyInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                   string          `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string          `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string          `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Protocols            []*ProtocolInfo `protobuf:"bytes,4,rep,name=protocols,proto3" json:"protocols,omitempty"`
	Assets               []*AssetInfo    `protobuf:"bytes,5,rep,name=assets,proto3" json:"assets,omitempty"`
	IsActive             bool            `protobuf:"varint,6,opt,name=isActive,proto3" json:"isActive,omitempty"`
	Logo                 string          `protobuf:"bytes,7,opt,name=logo,proto3" json:"logo,omitempty"`
	Status               string          `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	SessionSignerAddress string          `protobuf:"bytes,9,opt,name=sessionSignerAddress,proto3" json:"sessionSignerAddress,omitempty"`
	ChainId              string          `protobuf:"bytes,10,opt,name=chainId,proto3" json:"chainId,omitempty"`
	ActionIds            []string        `protobuf:"bytes,11,rep,name=actionIds,proto3" json:"actionIds,omitempty"`
	FeeToken             *FeeToken       `protobuf:"bytes,12,opt,name=feeToken,proto3" json:"feeToken,omitempty"`
	InputToken           string          `protobuf:"bytes,13,opt,name=inputToken,proto3" json:"inputToken,omitempty"`
	CreatedAt            string          `protobuf:"bytes,14,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            string          `protobuf:"bytes,15,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
}

func (x *StrategyInfo) Reset() {
	*x = StrategyInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_strategy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StrategyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StrategyInfo) ProtoMessage() {}

func (x *StrategyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_strategy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StrategyInfo.ProtoReflect.Descriptor instead.
func (*StrategyInfo) Descriptor() ([]byte, []int) {
	return file_strategy_models_strategy_proto_rawDescGZIP(), []int{2}
}

func (x *StrategyInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StrategyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StrategyInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *StrategyInfo) GetProtocols() []*ProtocolInfo {
	if x != nil {
		return x.Protocols
	}
	return nil
}

func (x *StrategyInfo) GetAssets() []*AssetInfo {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *StrategyInfo) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *StrategyInfo) GetLogo() string {
	if x != nil {
		return x.Logo
	}
	return ""
}

func (x *StrategyInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StrategyInfo) GetSessionSignerAddress() string {
	if x != nil {
		return x.SessionSignerAddress
	}
	return ""
}

func (x *StrategyInfo) GetChainId() string {
	if x != nil {
		return x.ChainId
	}
	return ""
}

func (x *StrategyInfo) GetActionIds() []string {
	if x != nil {
		return x.ActionIds
	}
	return nil
}

func (x *StrategyInfo) GetFeeToken() *FeeToken {
	if x != nil {
		return x.FeeToken
	}
	return nil
}

func (x *StrategyInfo) GetInputToken() string {
	if x != nil {
		return x.InputToken
	}
	return ""
}

func (x *StrategyInfo) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *StrategyInfo) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

type GetStrategyListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64           `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string          `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data []*StrategyInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *GetStrategyListResponse) Reset() {
	*x = GetStrategyListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_strategy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetStrategyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStrategyListResponse) ProtoMessage() {}

func (x *GetStrategyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_strategy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStrategyListResponse.ProtoReflect.Descriptor instead.
func (*GetStrategyListResponse) Descriptor() ([]byte, []int) {
	return file_strategy_models_strategy_proto_rawDescGZIP(), []int{3}
}

func (x *GetStrategyListResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetStrategyListResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetStrategyListResponse) GetData() []*StrategyInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type StartStrategyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrategyId  string `protobuf:"bytes,1,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	UserAddress string `protobuf:"bytes,2,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
	TxHash      string `protobuf:"bytes,3,opt,name=txHash,proto3" json:"txHash,omitempty"`
}

func (x *StartStrategyRequest) Reset() {
	*x = StartStrategyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_strategy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStrategyRequest) ProtoMessage() {}

func (x *StartStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_strategy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStrategyRequest.ProtoReflect.Descriptor instead.
func (*StartStrategyRequest) Descriptor() ([]byte, []int) {
	return file_strategy_models_strategy_proto_rawDescGZIP(), []int{4}
}

func (x *StartStrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *StartStrategyRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *StartStrategyRequest) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

type StartStrategyResponseData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount string `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (x *StartStrategyResponseData) Reset() {
	*x = StartStrategyResponseData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_strategy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartStrategyResponseData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStrategyResponseData) ProtoMessage() {}

func (x *StartStrategyResponseData) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_strategy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStrategyResponseData.ProtoReflect.Descriptor instead.
func (*StartStrategyResponseData) Descriptor() ([]byte, []int) {
	return file_strategy_models_strategy_proto_rawDescGZIP(), []int{5}
}

func (x *StartStrategyResponseData) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

type StartStrategyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64                      `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string                     `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *StartStrategyResponseData `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *StartStrategyResponse) Reset() {
	*x = StartStrategyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_strategy_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartStrategyResponse) ProtoMessage() {}

func (x *StartStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_strategy_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartStrategyResponse.ProtoReflect.Descriptor instead.
func (*StartStrategyResponse) Descriptor() ([]byte, []int) {
	return file_strategy_models_strategy_proto_rawDescGZIP(), []int{6}
}

func (x *StartStrategyResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *StartStrategyResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *StartStrategyResponse) GetData() *StartStrategyResponseData {
	if x != nil {
		return x.Data
	}
	return nil
}

type WithdrawStrategyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StrategyId  string `protobuf:"bytes,1,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	UserAddress string `protobuf:"bytes,2,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
}

func (x *WithdrawStrategyRequest) Reset() {
	*x = WithdrawStrategyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_strategy_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawStrategyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawStrategyRequest) ProtoMessage() {}

func (x *WithdrawStrategyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_strategy_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawStrategyRequest.ProtoReflect.Descriptor instead.
func (*WithdrawStrategyRequest) Descriptor() ([]byte, []int) {
	return file_strategy_models_strategy_proto_rawDescGZIP(), []int{7}
}

func (x *WithdrawStrategyRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *WithdrawStrategyRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

type WithdrawStrategyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *WithdrawStrategyResponse) Reset() {
	*x = WithdrawStrategyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategy_models_strategy_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WithdrawStrategyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawStrategyResponse) ProtoMessage() {}

func (x *WithdrawStrategyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategy_models_strategy_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawStrategyResponse.ProtoReflect.Descriptor instead.
func (*WithdrawStrategyResponse) Descriptor() ([]byte, []int) {
	return file_strategy_models_strategy_proto_rawDescGZIP(), []int{8}
}

func (x *WithdrawStrategyResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WithdrawStrategyResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_strategy_models_strategy_proto protoreflect.FileDescriptor

var file_strategy_models_strategy_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x08, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x1a, 0x1e, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x65, 0x67, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x61, 0x73, 0x73, 0x65,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x53, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3e, 0x0a, 0x08, 0x46, 0x65, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49,
	0x64, 0x22, 0xf7, 0x03, 0x0a, 0x0c, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x09, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x73, 0x12, 0x2b,
	0x0a, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13,
	0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2e, 0x41, 0x73, 0x73, 0x65, 0x74, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x06, 0x61, 0x73, 0x73, 0x65, 0x74, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x69,
	0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x69,
	0x73, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x6f, 0x67, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x32, 0x0a, 0x14, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x69,
	0x67, 0x6e, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x14, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x69, 0x67, 0x6e, 0x65, 0x72,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e,
	0x49, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49,
	0x64, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x18, 0x0b,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x73, 0x12,
	0x2e, 0x0a, 0x08, 0x66, 0x65, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2e, 0x46, 0x65, 0x65,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x08, 0x66, 0x65, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1e, 0x0a, 0x0a, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x1c, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0e, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a,
	0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x6b, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2a, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x73, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x2e, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x70, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x72,
	0x74, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64,
	0x12, 0x20, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x22, 0x33, 0x0a, 0x19, 0x53, 0x74,
	0x61, 0x72, 0x74, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x22,
	0x76, 0x0a, 0x15, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x37,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x73,
	0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x53, 0x74, 0x72,
	0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x61, 0x74,
	0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x5b, 0x0a, 0x17, 0x57, 0x69, 0x74, 0x68, 0x64,
	0x72, 0x61, 0x77, 0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79,
	0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x22, 0x40, 0x0a, 0x18, 0x57, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77,
	0x53, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x19, 0x5a, 0x17, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x3b, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67,
	0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_strategy_models_strategy_proto_rawDescOnce sync.Once
	file_strategy_models_strategy_proto_rawDescData = file_strategy_models_strategy_proto_rawDesc
)

func file_strategy_models_strategy_proto_rawDescGZIP() []byte {
	file_strategy_models_strategy_proto_rawDescOnce.Do(func() {
		file_strategy_models_strategy_proto_rawDescData = protoimpl.X.CompressGZIP(file_strategy_models_strategy_proto_rawDescData)
	})
	return file_strategy_models_strategy_proto_rawDescData
}

var file_strategy_models_strategy_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_strategy_models_strategy_proto_goTypes = []interface{}{
	(*GetStrategyListRequest)(nil),    // 0: strategy.GetStrategyListRequest
	(*FeeToken)(nil),                  // 1: strategy.FeeToken
	(*StrategyInfo)(nil),              // 2: strategy.StrategyInfo
	(*GetStrategyListResponse)(nil),   // 3: strategy.GetStrategyListResponse
	(*StartStrategyRequest)(nil),      // 4: strategy.StartStrategyRequest
	(*StartStrategyResponseData)(nil), // 5: strategy.StartStrategyResponseData
	(*StartStrategyResponse)(nil),     // 6: strategy.StartStrategyResponse
	(*WithdrawStrategyRequest)(nil),   // 7: strategy.WithdrawStrategyRequest
	(*WithdrawStrategyResponse)(nil),  // 8: strategy.WithdrawStrategyResponse
	(*ProtocolInfo)(nil),              // 9: strategy.ProtocolInfo
	(*AssetInfo)(nil),                 // 10: strategy.AssetInfo
}
var file_strategy_models_strategy_proto_depIdxs = []int32{
	9,  // 0: strategy.StrategyInfo.protocols:type_name -> strategy.ProtocolInfo
	10, // 1: strategy.StrategyInfo.assets:type_name -> strategy.AssetInfo
	1,  // 2: strategy.StrategyInfo.feeToken:type_name -> strategy.FeeToken
	2,  // 3: strategy.GetStrategyListResponse.data:type_name -> strategy.StrategyInfo
	5,  // 4: strategy.StartStrategyResponse.data:type_name -> strategy.StartStrategyResponseData
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_strategy_models_strategy_proto_init() }
func file_strategy_models_strategy_proto_init() {
	if File_strategy_models_strategy_proto != nil {
		return
	}
	file_strategy_models_protocol_proto_init()
	file_strategy_models_asset_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_strategy_models_strategy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStrategyListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_strategy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeeToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_strategy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StrategyInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_strategy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetStrategyListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_strategy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartStrategyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_strategy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartStrategyResponseData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_strategy_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartStrategyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_strategy_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawStrategyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategy_models_strategy_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WithdrawStrategyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_strategy_models_strategy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_strategy_models_strategy_proto_goTypes,
		DependencyIndexes: file_strategy_models_strategy_proto_depIdxs,
		MessageInfos:      file_strategy_models_strategy_proto_msgTypes,
	}.Build()
	File_strategy_models_strategy_proto = out.File
	file_strategy_models_strategy_proto_rawDesc = nil
	file_strategy_models_strategy_proto_goTypes = nil
	file_strategy_models_strategy_proto_depIdxs = nil
}
