// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.29.3
// source: strategyActivity/models/submitActivity.proto

package strategyActivity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubmitActivityRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Activity *Activity `protobuf:"bytes,1,opt,name=activity,proto3" json:"activity,omitempty"`
}

func (x *SubmitActivityRequest) Reset() {
	*x = SubmitActivityRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategyActivity_models_submitActivity_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitActivityRequest) ProtoMessage() {}

func (x *SubmitActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_strategyActivity_models_submitActivity_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitActivityRequest.ProtoReflect.Descriptor instead.
func (*SubmitActivityRequest) Descriptor() ([]byte, []int) {
	return file_strategyActivity_models_submitActivity_proto_rawDescGZIP(), []int{0}
}

func (x *SubmitActivityRequest) GetActivity() *Activity {
	if x != nil {
		return x.Activity
	}
	return nil
}

type SubmitActivityResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *SubmitActivityResponse) Reset() {
	*x = SubmitActivityResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_strategyActivity_models_submitActivity_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SubmitActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitActivityResponse) ProtoMessage() {}

func (x *SubmitActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_strategyActivity_models_submitActivity_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitActivityResponse.ProtoReflect.Descriptor instead.
func (*SubmitActivityResponse) Descriptor() ([]byte, []int) {
	return file_strategyActivity_models_submitActivity_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitActivityResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_strategyActivity_models_submitActivity_proto protoreflect.FileDescriptor

var file_strategyActivity_models_submitActivity_proto_rawDesc = []byte{
	0x0a, 0x2c, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x73, 0x75, 0x62, 0x6d, 0x69, 0x74,
	0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x1a, 0x29, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x67, 0x65, 0x74, 0x41, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x4f, 0x0a, 0x15, 0x53,
	0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x36, 0x0a, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67,
	0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x52, 0x08, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x22, 0x2a, 0x0a, 0x16,
	0x53, 0x75, 0x62, 0x6d, 0x69, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x42, 0x29, 0x5a, 0x27, 0x70, 0x62, 0x2f, 0x67,
	0x6f, 0x2f, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x3b, 0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x41, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x79, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_strategyActivity_models_submitActivity_proto_rawDescOnce sync.Once
	file_strategyActivity_models_submitActivity_proto_rawDescData = file_strategyActivity_models_submitActivity_proto_rawDesc
)

func file_strategyActivity_models_submitActivity_proto_rawDescGZIP() []byte {
	file_strategyActivity_models_submitActivity_proto_rawDescOnce.Do(func() {
		file_strategyActivity_models_submitActivity_proto_rawDescData = protoimpl.X.CompressGZIP(file_strategyActivity_models_submitActivity_proto_rawDescData)
	})
	return file_strategyActivity_models_submitActivity_proto_rawDescData
}

var file_strategyActivity_models_submitActivity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_strategyActivity_models_submitActivity_proto_goTypes = []interface{}{
	(*SubmitActivityRequest)(nil),  // 0: strategyActivity.SubmitActivityRequest
	(*SubmitActivityResponse)(nil), // 1: strategyActivity.SubmitActivityResponse
	(*Activity)(nil),               // 2: strategyActivity.Activity
}
var file_strategyActivity_models_submitActivity_proto_depIdxs = []int32{
	2, // 0: strategyActivity.SubmitActivityRequest.activity:type_name -> strategyActivity.Activity
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_strategyActivity_models_submitActivity_proto_init() }
func file_strategyActivity_models_submitActivity_proto_init() {
	if File_strategyActivity_models_submitActivity_proto != nil {
		return
	}
	file_strategyActivity_models_getActivity_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_strategyActivity_models_submitActivity_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitActivityRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_strategyActivity_models_submitActivity_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SubmitActivityResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_strategyActivity_models_submitActivity_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_strategyActivity_models_submitActivity_proto_goTypes,
		DependencyIndexes: file_strategyActivity_models_submitActivity_proto_depIdxs,
		MessageInfos:      file_strategyActivity_models_submitActivity_proto_msgTypes,
	}.Build()
	File_strategyActivity_models_submitActivity_proto = out.File
	file_strategyActivity_models_submitActivity_proto_rawDesc = nil
	file_strategyActivity_models_submitActivity_proto_goTypes = nil
	file_strategyActivity_models_submitActivity_proto_depIdxs = nil
}
