// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.29.3
// source: protocol/models/getSupplyLiquidityUniswapv3Balance.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSupplyLiquidityUniswapv3BalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PoolAddress string `protobuf:"bytes,1,opt,name=poolAddress,proto3" json:"poolAddress,omitempty"`
	UserAddress string `protobuf:"bytes,2,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
	ChainId     int64  `protobuf:"varint,3,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Protocol    string `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
}

func (x *GetSupplyLiquidityUniswapv3BalanceRequest) Reset() {
	*x = GetSupplyLiquidityUniswapv3BalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSupplyLiquidityUniswapv3BalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplyLiquidityUniswapv3BalanceRequest) ProtoMessage() {}

func (x *GetSupplyLiquidityUniswapv3BalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplyLiquidityUniswapv3BalanceRequest.ProtoReflect.Descriptor instead.
func (*GetSupplyLiquidityUniswapv3BalanceRequest) Descriptor() ([]byte, []int) {
	return file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_rawDescGZIP(), []int{0}
}

func (x *GetSupplyLiquidityUniswapv3BalanceRequest) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

func (x *GetSupplyLiquidityUniswapv3BalanceRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *GetSupplyLiquidityUniswapv3BalanceRequest) GetChainId() int64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetSupplyLiquidityUniswapv3BalanceRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type GetSupplyLiquidityUniswapv3BalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token0Address  string `protobuf:"bytes,1,opt,name=token0Address,proto3" json:"token0Address,omitempty"`
	Token1Address  string `protobuf:"bytes,2,opt,name=token1Address,proto3" json:"token1Address,omitempty"`
	Token0Amount   string `protobuf:"bytes,3,opt,name=token0Amount,proto3" json:"token0Amount,omitempty"`
	Token1Amount   string `protobuf:"bytes,4,opt,name=token1Amount,proto3" json:"token1Amount,omitempty"`
	Token0Decimals uint64 `protobuf:"varint,5,opt,name=token0Decimals,proto3" json:"token0Decimals,omitempty"`
	Token1Decimals uint64 `protobuf:"varint,6,opt,name=token1Decimals,proto3" json:"token1Decimals,omitempty"`
}

func (x *GetSupplyLiquidityUniswapv3BalanceResponse) Reset() {
	*x = GetSupplyLiquidityUniswapv3BalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSupplyLiquidityUniswapv3BalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSupplyLiquidityUniswapv3BalanceResponse) ProtoMessage() {}

func (x *GetSupplyLiquidityUniswapv3BalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSupplyLiquidityUniswapv3BalanceResponse.ProtoReflect.Descriptor instead.
func (*GetSupplyLiquidityUniswapv3BalanceResponse) Descriptor() ([]byte, []int) {
	return file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_rawDescGZIP(), []int{1}
}

func (x *GetSupplyLiquidityUniswapv3BalanceResponse) GetToken0Address() string {
	if x != nil {
		return x.Token0Address
	}
	return ""
}

func (x *GetSupplyLiquidityUniswapv3BalanceResponse) GetToken1Address() string {
	if x != nil {
		return x.Token1Address
	}
	return ""
}

func (x *GetSupplyLiquidityUniswapv3BalanceResponse) GetToken0Amount() string {
	if x != nil {
		return x.Token0Amount
	}
	return ""
}

func (x *GetSupplyLiquidityUniswapv3BalanceResponse) GetToken1Amount() string {
	if x != nil {
		return x.Token1Amount
	}
	return ""
}

func (x *GetSupplyLiquidityUniswapv3BalanceResponse) GetToken0Decimals() uint64 {
	if x != nil {
		return x.Token0Decimals
	}
	return 0
}

func (x *GetSupplyLiquidityUniswapv3BalanceResponse) GetToken1Decimals() uint64 {
	if x != nil {
		return x.Token1Decimals
	}
	return 0
}

var File_protocol_models_getSupplyLiquidityUniswapv3Balance_proto protoreflect.FileDescriptor

var file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_rawDesc = []byte{
	0x0a, 0x38, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x67, 0x65, 0x74, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x71, 0x75, 0x69,
	0x64, 0x69, 0x74, 0x79, 0x55, 0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x76, 0x33, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x6f, 0x6c, 0x22, 0xa5, 0x01, 0x0a, 0x29, 0x47, 0x65, 0x74, 0x53, 0x75, 0x70, 0x70,
	0x6c, 0x79, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64, 0x69, 0x74, 0x79, 0x55, 0x6e, 0x69, 0x73, 0x77,
	0x61, 0x70, 0x76, 0x33, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6f, 0x6f, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x6f, 0x6f, 0x6c, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22, 0x90, 0x02, 0x0a,
	0x2a, 0x47, 0x65, 0x74, 0x53, 0x75, 0x70, 0x70, 0x6c, 0x79, 0x4c, 0x69, 0x71, 0x75, 0x69, 0x64,
	0x69, 0x74, 0x79, 0x55, 0x6e, 0x69, 0x73, 0x77, 0x61, 0x70, 0x76, 0x33, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x24, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x30, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x26, 0x0a, 0x0e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x30, 0x44,
	0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x26, 0x0a, 0x0e, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x31, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x31, 0x44, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x42,
	0x19, 0x5a, 0x17, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f,
	0x6c, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_rawDescOnce sync.Once
	file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_rawDescData = file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_rawDesc
)

func file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_rawDescGZIP() []byte {
	file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_rawDescOnce.Do(func() {
		file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_rawDescData)
	})
	return file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_rawDescData
}

var file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_goTypes = []interface{}{
	(*GetSupplyLiquidityUniswapv3BalanceRequest)(nil),  // 0: protocol.GetSupplyLiquidityUniswapv3BalanceRequest
	(*GetSupplyLiquidityUniswapv3BalanceResponse)(nil), // 1: protocol.GetSupplyLiquidityUniswapv3BalanceResponse
}
var file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_init() }
func file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_init() {
	if File_protocol_models_getSupplyLiquidityUniswapv3Balance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSupplyLiquidityUniswapv3BalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSupplyLiquidityUniswapv3BalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_goTypes,
		DependencyIndexes: file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_depIdxs,
		MessageInfos:      file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_msgTypes,
	}.Build()
	File_protocol_models_getSupplyLiquidityUniswapv3Balance_proto = out.File
	file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_rawDesc = nil
	file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_goTypes = nil
	file_protocol_models_getSupplyLiquidityUniswapv3Balance_proto_depIdxs = nil
}
