// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v5.29.3
// source: protocol/models/withdrawERC20.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BorrowedBalanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAddress  string `protobuf:"bytes,1,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
	TokenAddress string `protobuf:"bytes,2,opt,name=tokenAddress,proto3" json:"tokenAddress,omitempty"` // supplied token address
	ChainID      int64  `protobuf:"varint,3,opt,name=ChainID,proto3" json:"ChainID,omitempty"`
	PoolAddress  string `protobuf:"bytes,4,opt,name=poolAddress,proto3" json:"poolAddress,omitempty"`
}

func (x *BorrowedBalanceRequest) Reset() {
	*x = BorrowedBalanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_models_withdrawERC20_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowedBalanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowedBalanceRequest) ProtoMessage() {}

func (x *BorrowedBalanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_models_withdrawERC20_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowedBalanceRequest.ProtoReflect.Descriptor instead.
func (*BorrowedBalanceRequest) Descriptor() ([]byte, []int) {
	return file_protocol_models_withdrawERC20_proto_rawDescGZIP(), []int{0}
}

func (x *BorrowedBalanceRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *BorrowedBalanceRequest) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *BorrowedBalanceRequest) GetChainID() int64 {
	if x != nil {
		return x.ChainID
	}
	return 0
}

func (x *BorrowedBalanceRequest) GetPoolAddress() string {
	if x != nil {
		return x.PoolAddress
	}
	return ""
}

type BorrowedBalanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenAddress string `protobuf:"bytes,1,opt,name=tokenAddress,proto3" json:"tokenAddress,omitempty"`
	Balance      string `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	Decimals     string `protobuf:"bytes,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
}

func (x *BorrowedBalanceResponse) Reset() {
	*x = BorrowedBalanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protocol_models_withdrawERC20_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BorrowedBalanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowedBalanceResponse) ProtoMessage() {}

func (x *BorrowedBalanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_models_withdrawERC20_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowedBalanceResponse.ProtoReflect.Descriptor instead.
func (*BorrowedBalanceResponse) Descriptor() ([]byte, []int) {
	return file_protocol_models_withdrawERC20_proto_rawDescGZIP(), []int{1}
}

func (x *BorrowedBalanceResponse) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *BorrowedBalanceResponse) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *BorrowedBalanceResponse) GetDecimals() string {
	if x != nil {
		return x.Decimals
	}
	return ""
}

var File_protocol_models_withdrawERC20_proto protoreflect.FileDescriptor

var file_protocol_models_withdrawERC20_proto_rawDesc = []byte{
	0x0a, 0x23, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x77, 0x69, 0x74, 0x68, 0x64, 0x72, 0x61, 0x77, 0x45, 0x52, 0x43, 0x32, 0x30, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x22,
	0x9a, 0x01, 0x0a, 0x16, 0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x64, 0x42, 0x61, 0x6c, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x73,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x22, 0x0a, 0x0c,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x44, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x6f,
	0x6f, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x70, 0x6f, 0x6f, 0x6c, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x73, 0x0a, 0x17,
	0x42, 0x6f, 0x72, 0x72, 0x6f, 0x77, 0x65, 0x64, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x62,
	0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x62, 0x61,
	0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x63, 0x69, 0x6d, 0x61, 0x6c,
	0x73, 0x42, 0x19, 0x5a, 0x17, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protocol_models_withdrawERC20_proto_rawDescOnce sync.Once
	file_protocol_models_withdrawERC20_proto_rawDescData = file_protocol_models_withdrawERC20_proto_rawDesc
)

func file_protocol_models_withdrawERC20_proto_rawDescGZIP() []byte {
	file_protocol_models_withdrawERC20_proto_rawDescOnce.Do(func() {
		file_protocol_models_withdrawERC20_proto_rawDescData = protoimpl.X.CompressGZIP(file_protocol_models_withdrawERC20_proto_rawDescData)
	})
	return file_protocol_models_withdrawERC20_proto_rawDescData
}

var file_protocol_models_withdrawERC20_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protocol_models_withdrawERC20_proto_goTypes = []interface{}{
	(*BorrowedBalanceRequest)(nil),  // 0: protocol.BorrowedBalanceRequest
	(*BorrowedBalanceResponse)(nil), // 1: protocol.BorrowedBalanceResponse
}
var file_protocol_models_withdrawERC20_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_models_withdrawERC20_proto_init() }
func file_protocol_models_withdrawERC20_proto_init() {
	if File_protocol_models_withdrawERC20_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protocol_models_withdrawERC20_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrowedBalanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protocol_models_withdrawERC20_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BorrowedBalanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protocol_models_withdrawERC20_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_models_withdrawERC20_proto_goTypes,
		DependencyIndexes: file_protocol_models_withdrawERC20_proto_depIdxs,
		MessageInfos:      file_protocol_models_withdrawERC20_proto_msgTypes,
	}.Build()
	File_protocol_models_withdrawERC20_proto = out.File
	file_protocol_models_withdrawERC20_proto_rawDesc = nil
	file_protocol_models_withdrawERC20_proto_goTypes = nil
	file_protocol_models_withdrawERC20_proto_depIdxs = nil
}
