// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: compound/models/getAPR.proto

/* eslint-disable */

export const protobufPackage = "compound";

export interface GetAPRRequest {
}

export interface GetAPRResponse {
  supplyAPR: string;
  borrowAPR: string;
}

export const COMPOUND_PACKAGE_NAME = "compound";
