// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: compound/models/supplyERC20.proto

/* eslint-disable */

export const protobufPackage = "compound";

export interface SupplyERC20Request {
  userAddress: string;
  strategyId: string;
  amount: string;
  assetAddress: string;
  orchestratorAddress: string;
}

export interface SupplyERC20Response {
  chainId: number;
  txHash: string;
  amount: string;
}

export interface SuppliedBalanceRequest {
  userAddress: string;
  /** supplied token address */
  tokenAddress: string;
}

export interface SuppliedBalanceResponse {
  tokenAddress: string;
  supplyBalance: string;
  borrowBalance: string;
}

export const COMPOUND_PACKAGE_NAME = "compound";
