// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: compound/models/withdrawERC20.proto

/* eslint-disable */

export const protobufPackage = "compound";

export interface WithdrawERC20Request {
  userAddress: string;
  strategyId: string;
  assetAddress: string;
  amount: string;
  orchestratorAddress: string;
}

export interface WithdrawERC20Response {
  chainId: number;
  txHash: string;
  amount: string;
}

export const COMPOUND_PACKAGE_NAME = "compound";
