// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: morpho/models/getAPR.proto

/* eslint-disable */

export const protobufPackage = "morpho";

export interface GetAPRRequest {
  tokenAddress: string;
  poolAddress: string;
  chainId: number;
}

export interface GetAPRResponse {
  supplyAPR: string;
  borrowAPR: string;
}

export const MORPHO_PACKAGE_NAME = "morpho";
