// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: morpho/models/getLendingPool.proto

/* eslint-disable */

export const protobufPackage = "morpho";

export interface GetLendingPoolRequest {
  chainId: number;
}

export interface GetLendingPoolResponse {
  poolAddress: string[];
}

export const MORPHO_PACKAGE_NAME = "morpho";
