// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: morpho/models/getLiquidity.proto

/* eslint-disable */

export const protobufPackage = "morpho";

export interface GetLiquidityRequest {
  tokenAddress: string;
  poolAddress: string;
  chainId: number;
}

export interface GetLiquidityResponse {
  Liquidity: number;
}

export const MORPHO_PACKAGE_NAME = "morpho";
