// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: morpho/models/getTVL.proto

/* eslint-disable */

export const protobufPackage = "morpho";

export interface GetTVLRequest {
  tokenAddress: string;
  poolAddress: string;
  chainId: number;
}

export interface GetTVLResponse {
  TVL: number;
}

export const MORPHO_PACKAGE_NAME = "morpho";
