// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: morpho/models/supplyERC20.proto

/* eslint-disable */

export const protobufPackage = "morpho";

export interface SupplyERC20Request {
  userAddress: string;
  orchestratorAddress: string;
  strategyId: string;
  poolAddress: string;
  amount: string;
  assetAddress: string;
  chainId: number;
}

export interface SupplyERC20Response {
  chainId: number;
  txHash: string;
  amount: string;
}

export const MORPHO_PACKAGE_NAME = "morpho";
