// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: thirdweb/service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { UsePermissionRequest, UsePermissionResponse } from "./models/usePermission";

export const protobufPackage = "thirdweb";

export const THIRDWEB_PACKAGE_NAME = "thirdweb";

export interface ThirdwebServiceClient {
  usePermission(request: UsePermissionRequest): Observable<UsePermissionResponse>;
}

export interface ThirdwebServiceController {
  usePermission(
    request: UsePermissionRequest,
  ): Promise<UsePermissionResponse> | Observable<UsePermissionResponse> | UsePermissionResponse;
}

export function ThirdwebServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["usePermission"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ThirdwebService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ThirdwebService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const THIRDWEB_SERVICE_NAME = "ThirdwebService";
