// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: thirdweb/models/usePermission.proto

/* eslint-disable */

export const protobufPackage = "thirdweb";

export interface UsePermissionRequest {
  orchestratorAddress: string;
  strategyId: string;
  target: string;
  callData: string;
  referenceId: string;
  chainId: number;
  value: string;
  permissionId: string;
}

export interface UsePermissionResponse {
  txHash: string;
  transactionStatus: string;
}

export const THIRDWEB_PACKAGE_NAME = "thirdweb";
