// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.30.0--rc1
// source: thirdweb/service.proto

package thirdweb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ThirdwebService_UsePermission_FullMethodName = "/thirdweb.ThirdwebService/UsePermission"
)

// ThirdwebServiceClient is the client API for ThirdwebService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThirdwebServiceClient interface {
	UsePermission(ctx context.Context, in *UsePermissionRequest, opts ...grpc.CallOption) (*UsePermissionResponse, error)
}

type thirdwebServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewThirdwebServiceClient(cc grpc.ClientConnInterface) ThirdwebServiceClient {
	return &thirdwebServiceClient{cc}
}

func (c *thirdwebServiceClient) UsePermission(ctx context.Context, in *UsePermissionRequest, opts ...grpc.CallOption) (*UsePermissionResponse, error) {
	out := new(UsePermissionResponse)
	err := c.cc.Invoke(ctx, ThirdwebService_UsePermission_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThirdwebServiceServer is the server API for ThirdwebService service.
// All implementations should embed UnimplementedThirdwebServiceServer
// for forward compatibility
type ThirdwebServiceServer interface {
	UsePermission(context.Context, *UsePermissionRequest) (*UsePermissionResponse, error)
}

// UnimplementedThirdwebServiceServer should be embedded to have forward compatible implementations.
type UnimplementedThirdwebServiceServer struct {
}

func (UnimplementedThirdwebServiceServer) UsePermission(context.Context, *UsePermissionRequest) (*UsePermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UsePermission not implemented")
}

// UnsafeThirdwebServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThirdwebServiceServer will
// result in compilation errors.
type UnsafeThirdwebServiceServer interface {
	mustEmbedUnimplementedThirdwebServiceServer()
}

func RegisterThirdwebServiceServer(s grpc.ServiceRegistrar, srv ThirdwebServiceServer) {
	s.RegisterService(&ThirdwebService_ServiceDesc, srv)
}

func _ThirdwebService_UsePermission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsePermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThirdwebServiceServer).UsePermission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ThirdwebService_UsePermission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThirdwebServiceServer).UsePermission(ctx, req.(*UsePermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThirdwebService_ServiceDesc is the grpc.ServiceDesc for ThirdwebService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThirdwebService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thirdweb.ThirdwebService",
	HandlerType: (*ThirdwebServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UsePermission",
			Handler:    _ThirdwebService_UsePermission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thirdweb/service.proto",
}
