// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.30.0--rc1
// source: thirdweb/models/usePermission.proto

package thirdweb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UsePermissionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrchestratorAddress string `protobuf:"bytes,1,opt,name=orchestratorAddress,proto3" json:"orchestratorAddress,omitempty"`
	StrategyId          string `protobuf:"bytes,2,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	Target              string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	CallData            string `protobuf:"bytes,4,opt,name=callData,proto3" json:"callData,omitempty"`
	ReferenceId         string `protobuf:"bytes,5,opt,name=referenceId,proto3" json:"referenceId,omitempty"`
	ChainId             int32  `protobuf:"varint,6,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Value               string `protobuf:"bytes,7,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *UsePermissionRequest) Reset() {
	*x = UsePermissionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thirdweb_models_usePermission_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsePermissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsePermissionRequest) ProtoMessage() {}

func (x *UsePermissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_thirdweb_models_usePermission_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsePermissionRequest.ProtoReflect.Descriptor instead.
func (*UsePermissionRequest) Descriptor() ([]byte, []int) {
	return file_thirdweb_models_usePermission_proto_rawDescGZIP(), []int{0}
}

func (x *UsePermissionRequest) GetOrchestratorAddress() string {
	if x != nil {
		return x.OrchestratorAddress
	}
	return ""
}

func (x *UsePermissionRequest) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *UsePermissionRequest) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *UsePermissionRequest) GetCallData() string {
	if x != nil {
		return x.CallData
	}
	return ""
}

func (x *UsePermissionRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *UsePermissionRequest) GetChainId() int32 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *UsePermissionRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type UsePermissionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHash            string `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	TransactionStatus string `protobuf:"bytes,2,opt,name=transactionStatus,proto3" json:"transactionStatus,omitempty"`
}

func (x *UsePermissionResponse) Reset() {
	*x = UsePermissionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_thirdweb_models_usePermission_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsePermissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsePermissionResponse) ProtoMessage() {}

func (x *UsePermissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_thirdweb_models_usePermission_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsePermissionResponse.ProtoReflect.Descriptor instead.
func (*UsePermissionResponse) Descriptor() ([]byte, []int) {
	return file_thirdweb_models_usePermission_proto_rawDescGZIP(), []int{1}
}

func (x *UsePermissionResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *UsePermissionResponse) GetTransactionStatus() string {
	if x != nil {
		return x.TransactionStatus
	}
	return ""
}

var File_thirdweb_models_usePermission_proto protoreflect.FileDescriptor

var file_thirdweb_models_usePermission_proto_rawDesc = []byte{
	0x0a, 0x23, 0x74, 0x68, 0x69, 0x72, 0x64, 0x77, 0x65, 0x62, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x75, 0x73, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x74, 0x68, 0x69, 0x72, 0x64, 0x77, 0x65, 0x62, 0x22,
	0xee, 0x01, 0x0a, 0x14, 0x55, 0x73, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x13, 0x6f, 0x72, 0x63, 0x68,
	0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x61,
	0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20,
	0x0a, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x72, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x49, 0x64,
	0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x22, 0x5d, 0x0a, 0x15, 0x55, 0x73, 0x65, 0x50, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x48,
	0x61, 0x73, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73,
	0x68, 0x12, 0x2c, 0x0a, 0x11, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42,
	0x19, 0x5a, 0x17, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x74, 0x68, 0x69, 0x72, 0x64, 0x77, 0x65,
	0x62, 0x3b, 0x74, 0x68, 0x69, 0x72, 0x64, 0x77, 0x65, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_thirdweb_models_usePermission_proto_rawDescOnce sync.Once
	file_thirdweb_models_usePermission_proto_rawDescData = file_thirdweb_models_usePermission_proto_rawDesc
)

func file_thirdweb_models_usePermission_proto_rawDescGZIP() []byte {
	file_thirdweb_models_usePermission_proto_rawDescOnce.Do(func() {
		file_thirdweb_models_usePermission_proto_rawDescData = protoimpl.X.CompressGZIP(file_thirdweb_models_usePermission_proto_rawDescData)
	})
	return file_thirdweb_models_usePermission_proto_rawDescData
}

var file_thirdweb_models_usePermission_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_thirdweb_models_usePermission_proto_goTypes = []interface{}{
	(*UsePermissionRequest)(nil),  // 0: thirdweb.UsePermissionRequest
	(*UsePermissionResponse)(nil), // 1: thirdweb.UsePermissionResponse
}
var file_thirdweb_models_usePermission_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_thirdweb_models_usePermission_proto_init() }
func file_thirdweb_models_usePermission_proto_init() {
	if File_thirdweb_models_usePermission_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_thirdweb_models_usePermission_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsePermissionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_thirdweb_models_usePermission_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsePermissionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_thirdweb_models_usePermission_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_thirdweb_models_usePermission_proto_goTypes,
		DependencyIndexes: file_thirdweb_models_usePermission_proto_depIdxs,
		MessageInfos:      file_thirdweb_models_usePermission_proto_msgTypes,
	}.Build()
	File_thirdweb_models_usePermission_proto = out.File
	file_thirdweb_models_usePermission_proto_rawDesc = nil
	file_thirdweb_models_usePermission_proto_goTypes = nil
	file_thirdweb_models_usePermission_proto_depIdxs = nil
}
