// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v6.30.0--rc1
// source: hypurrfi/models/approveERC20.proto

package hypurrfi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApproveERC20Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserAddress         string `protobuf:"bytes,1,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
	OrchestratorAddress string `protobuf:"bytes,2,opt,name=orchestratorAddress,proto3" json:"orchestratorAddress,omitempty"`
	StrategyId          string `protobuf:"bytes,3,opt,name=strategyId,proto3" json:"strategyId,omitempty"`
	SpenderAddress      string `protobuf:"bytes,4,opt,name=spenderAddress,proto3" json:"spenderAddress,omitempty"`
	Amount              string `protobuf:"bytes,5,opt,name=amount,proto3" json:"amount,omitempty"`
	AssetAddress        string `protobuf:"bytes,6,opt,name=assetAddress,proto3" json:"assetAddress,omitempty"`
	PermissionId        string `protobuf:"bytes,7,opt,name=permissionId,proto3" json:"permissionId,omitempty"`
}

func (x *ApproveERC20Request) Reset() {
	*x = ApproveERC20Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypurrfi_models_approveERC20_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApproveERC20Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveERC20Request) ProtoMessage() {}

func (x *ApproveERC20Request) ProtoReflect() protoreflect.Message {
	mi := &file_hypurrfi_models_approveERC20_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveERC20Request.ProtoReflect.Descriptor instead.
func (*ApproveERC20Request) Descriptor() ([]byte, []int) {
	return file_hypurrfi_models_approveERC20_proto_rawDescGZIP(), []int{0}
}

func (x *ApproveERC20Request) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *ApproveERC20Request) GetOrchestratorAddress() string {
	if x != nil {
		return x.OrchestratorAddress
	}
	return ""
}

func (x *ApproveERC20Request) GetStrategyId() string {
	if x != nil {
		return x.StrategyId
	}
	return ""
}

func (x *ApproveERC20Request) GetSpenderAddress() string {
	if x != nil {
		return x.SpenderAddress
	}
	return ""
}

func (x *ApproveERC20Request) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ApproveERC20Request) GetAssetAddress() string {
	if x != nil {
		return x.AssetAddress
	}
	return ""
}

func (x *ApproveERC20Request) GetPermissionId() string {
	if x != nil {
		return x.PermissionId
	}
	return ""
}

type ApproveERC20Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TxHash      string `protobuf:"bytes,1,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Amount      string `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	SuperTxHash string `protobuf:"bytes,3,opt,name=superTxHash,proto3" json:"superTxHash,omitempty"`
}

func (x *ApproveERC20Data) Reset() {
	*x = ApproveERC20Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypurrfi_models_approveERC20_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApproveERC20Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveERC20Data) ProtoMessage() {}

func (x *ApproveERC20Data) ProtoReflect() protoreflect.Message {
	mi := &file_hypurrfi_models_approveERC20_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveERC20Data.ProtoReflect.Descriptor instead.
func (*ApproveERC20Data) Descriptor() ([]byte, []int) {
	return file_hypurrfi_models_approveERC20_proto_rawDescGZIP(), []int{1}
}

func (x *ApproveERC20Data) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *ApproveERC20Data) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *ApproveERC20Data) GetSuperTxHash() string {
	if x != nil {
		return x.SuperTxHash
	}
	return ""
}

type ApproveERC20Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int64             `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string            `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *ApproveERC20Data `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *ApproveERC20Response) Reset() {
	*x = ApproveERC20Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hypurrfi_models_approveERC20_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ApproveERC20Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApproveERC20Response) ProtoMessage() {}

func (x *ApproveERC20Response) ProtoReflect() protoreflect.Message {
	mi := &file_hypurrfi_models_approveERC20_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApproveERC20Response.ProtoReflect.Descriptor instead.
func (*ApproveERC20Response) Descriptor() ([]byte, []int) {
	return file_hypurrfi_models_approveERC20_proto_rawDescGZIP(), []int{2}
}

func (x *ApproveERC20Response) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApproveERC20Response) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ApproveERC20Response) GetData() *ApproveERC20Data {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_hypurrfi_models_approveERC20_proto protoreflect.FileDescriptor

var file_hypurrfi_models_approveERC20_proto_rawDesc = []byte{
	0x0a, 0x22, 0x68, 0x79, 0x70, 0x75, 0x72, 0x72, 0x66, 0x69, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x73, 0x2f, 0x61, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x45, 0x52, 0x43, 0x32, 0x30, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x68, 0x79, 0x70, 0x75, 0x72, 0x72, 0x66, 0x69, 0x22, 0x91,
	0x02, 0x0a, 0x13, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x45, 0x52, 0x43, 0x32, 0x30, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x75, 0x73, 0x65, 0x72, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x75, 0x73, 0x65,
	0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x30, 0x0a, 0x13, 0x6f, 0x72, 0x63, 0x68,
	0x65, 0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x6f, 0x72, 0x63, 0x68, 0x65, 0x73, 0x74, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x65, 0x67, 0x79, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x73, 0x70,
	0x65, 0x6e, 0x64, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0e, 0x73, 0x70, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x73,
	0x73, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x61, 0x73, 0x73, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x22,
	0x0a, 0x0c, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x64, 0x22, 0x64, 0x0a, 0x10, 0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x45, 0x52, 0x43,
	0x32, 0x30, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x16,
	0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x73, 0x75, 0x70, 0x65, 0x72, 0x54,
	0x78, 0x48, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x73, 0x75, 0x70,
	0x65, 0x72, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x22, 0x6c, 0x0a, 0x14, 0x41, 0x70, 0x70, 0x72,
	0x6f, 0x76, 0x65, 0x45, 0x52, 0x43, 0x32, 0x30, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2e, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x68, 0x79, 0x70, 0x75, 0x72, 0x72, 0x66, 0x69, 0x2e,
	0x41, 0x70, 0x70, 0x72, 0x6f, 0x76, 0x65, 0x45, 0x52, 0x43, 0x32, 0x30, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x42, 0x19, 0x5a, 0x17, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f,
	0x68, 0x79, 0x70, 0x75, 0x72, 0x72, 0x66, 0x69, 0x3b, 0x68, 0x79, 0x70, 0x75, 0x72, 0x72, 0x66,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hypurrfi_models_approveERC20_proto_rawDescOnce sync.Once
	file_hypurrfi_models_approveERC20_proto_rawDescData = file_hypurrfi_models_approveERC20_proto_rawDesc
)

func file_hypurrfi_models_approveERC20_proto_rawDescGZIP() []byte {
	file_hypurrfi_models_approveERC20_proto_rawDescOnce.Do(func() {
		file_hypurrfi_models_approveERC20_proto_rawDescData = protoimpl.X.CompressGZIP(file_hypurrfi_models_approveERC20_proto_rawDescData)
	})
	return file_hypurrfi_models_approveERC20_proto_rawDescData
}

var file_hypurrfi_models_approveERC20_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_hypurrfi_models_approveERC20_proto_goTypes = []interface{}{
	(*ApproveERC20Request)(nil),  // 0: hypurrfi.ApproveERC20Request
	(*ApproveERC20Data)(nil),     // 1: hypurrfi.ApproveERC20Data
	(*ApproveERC20Response)(nil), // 2: hypurrfi.ApproveERC20Response
}
var file_hypurrfi_models_approveERC20_proto_depIdxs = []int32{
	1, // 0: hypurrfi.ApproveERC20Response.data:type_name -> hypurrfi.ApproveERC20Data
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hypurrfi_models_approveERC20_proto_init() }
func file_hypurrfi_models_approveERC20_proto_init() {
	if File_hypurrfi_models_approveERC20_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_hypurrfi_models_approveERC20_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApproveERC20Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hypurrfi_models_approveERC20_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApproveERC20Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hypurrfi_models_approveERC20_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ApproveERC20Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hypurrfi_models_approveERC20_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hypurrfi_models_approveERC20_proto_goTypes,
		DependencyIndexes: file_hypurrfi_models_approveERC20_proto_depIdxs,
		MessageInfos:      file_hypurrfi_models_approveERC20_proto_msgTypes,
	}.Build()
	File_hypurrfi_models_approveERC20_proto = out.File
	file_hypurrfi_models_approveERC20_proto_rawDesc = nil
	file_hypurrfi_models_approveERC20_proto_goTypes = nil
	file_hypurrfi_models_approveERC20_proto_depIdxs = nil
}
