// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: strategy/models/account.proto

/* eslint-disable */

export const protobufPackage = "strategy";

export interface GetBiconomyAccountRequest {
  userAddress: string;
}

export interface BiconomyAccountInfo {
  userAddress: string;
  orchestratorAddress: string;
  chainId: number;
  index: number;
  strategyId: string;
}

export interface GetBiconomyAccountResponse {
  code: number;
  msg: string;
  data: BiconomyAccountInfo[];
}

export const STRATEGY_PACKAGE_NAME = "strategy";
