// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: strategy/models/apy.proto

/* eslint-disable */

export const protobufPackage = "strategy";

export interface GetAPYRequest {
  strategyId: string;
  amount: string;
}

export interface APYInfo {
  yieldAmount: string;
  borrowFeeAmount: string;
  finalYieldAmount: string;
  inputAmount: string;
}

export interface GetAPYResponse {
  code: number;
  msg: string;
  data: APYInfo | undefined;
}

export const STRATEGY_PACKAGE_NAME = "strategy";
