// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: strategy/models/asset.proto

/* eslint-disable */

export const protobufPackage = "strategy";

export interface AssetInfo {
  id: string;
  name: string;
  chainName: string;
  chainId: string;
  tokenAddress: string;
  tokenDecimals: number;
  tokenSymbol: string;
  logo: string;
  minAmount: string;
  maxAmount: string;
  createdAt: string;
  updatedAt: string;
}

export const STRATEGY_PACKAGE_NAME = "strategy";
