// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: strategy/models/balance.proto

/* eslint-disable */

export const protobufPackage = "strategy";

export interface GetProtocolBalanceRequest {
  strategyId: string;
  userAddress: string;
  chainId: string;
}

export interface ProtocolBalanceInfo {
  type: string;
  protocolName: string;
  tokenAddress: string;
  amount: string;
  decimals: string;
  action: string;
}

export interface GetProtocolBalanceResponse {
  code: number;
  msg: string;
  data: ProtocolBalanceInfo[];
}

export const STRATEGY_PACKAGE_NAME = "strategy";
