// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: strategy/models/health.proto

/* eslint-disable */

export const protobufPackage = "strategy";

export interface GetHealthRequest {
}

export interface GetHealthResponse {
  status: string;
}

export const STRATEGY_PACKAGE_NAME = "strategy";
