// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: strategy/models/jobs.proto

/* eslint-disable */

export const protobufPackage = "strategy";

export interface GetUserJobsRequest {
  userAddress: string;
}

export interface UserJobInfo {
  jobId: string;
  currentStep: number;
  totalSteps: number;
  strategyId: string;
  action: string;
}

export interface GetUserJobsResponse {
  code: number;
  msg: string;
  data: UserJobInfo[];
}

export interface GetCurrentStepRequest {
  jobId: string;
}

export interface CurrentStepInfo {
  currentStep: number;
  stepName: string;
  totalSteps: number;
  strategyId: string;
  type: string;
}

export interface GetCurrentStepResponse {
  code: number;
  msg: string;
  data: CurrentStepInfo | undefined;
}

export const STRATEGY_PACKAGE_NAME = "strategy";
