// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: strategy/models/protocol.proto

/* eslint-disable */

export const protobufPackage = "strategy";

export interface ProtocolInfo {
  id: string;
  name: string;
  description: string;
  protocol: string;
  link: string;
  logo: string;
}

export const STRATEGY_PACKAGE_NAME = "strategy";
