// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: strategy/models/strategy.proto

/* eslint-disable */
import { AssetInfo } from "./asset";
import { ProtocolInfo } from "./protocol";

export const protobufPackage = "strategy";

export interface GetStrategyListRequest {
}

export interface FeeToken {
  address: string;
  chainId: string;
}

export interface StrategyInfo {
  id: string;
  name: string;
  description: string;
  protocols: ProtocolInfo[];
  assets: AssetInfo[];
  isActive: boolean;
  logo: string;
  status: string;
  sessionSignerAddress: string;
  chainId: string;
  actionIds: string[];
  feeToken: FeeToken | undefined;
  inputToken: string;
  createdAt: string;
  updatedAt: string;
}

export interface GetStrategyListResponse {
  code: number;
  msg: string;
  data: StrategyInfo[];
}

export interface StartStrategyRequest {
  strategyId: string;
  userAddress: string;
  txHash: string;
}

export interface StartStrategyResponseData {
  amount: string;
}

export interface StartStrategyResponse {
  code: number;
  msg: string;
  data: StartStrategyResponseData | undefined;
}

export interface WithdrawStrategyRequest {
  strategyId: string;
  userAddress: string;
}

export interface WithdrawStrategyResponse {
  code: number;
  msg: string;
}

export const STRATEGY_PACKAGE_NAME = "strategy";
