// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.0
// source: morpho/service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";
import { GetAPRRequest, GetAPRResponse } from "./models/getAPR";
import { GetAPYRequest, GetAPYResponse } from "./models/getAPY";
import { GetLendingPoolRequest, GetLendingPoolResponse } from "./models/getLendingPool";
import { GetLiquidityRequest, GetLiquidityResponse } from "./models/getLiquidity";
import { GetTVLRequest, GetTVLResponse } from "./models/getTVL";
import {
  SuppliedBalanceRequest,
  SuppliedBalanceResponse,
  SupplyERC20Request,
  SupplyERC20Response,
} from "./models/supplyERC20";
import { WithdrawERC20Request, WithdrawERC20Response } from "./models/withdrawERC20";

export const protobufPackage = "morpho";

export const MORPHO_PACKAGE_NAME = "morpho";

export interface MorphoServiceClient {
  supplyErc20(request: SupplyERC20Request): Observable<SupplyERC20Response>;

  withdrawErc20(request: WithdrawERC20Request): Observable<WithdrawERC20Response>;

  getApr(request: GetAPRRequest): Observable<GetAPRResponse>;

  getApy(request: GetAPYRequest): Observable<GetAPYResponse>;

  getTvl(request: GetTVLRequest): Observable<GetTVLResponse>;

  getLiquidity(request: GetLiquidityRequest): Observable<GetLiquidityResponse>;

  getSuppliedBalance(request: SuppliedBalanceRequest): Observable<SuppliedBalanceResponse>;

  getLendingPool(request: GetLendingPoolRequest): Observable<GetLendingPoolResponse>;
}

export interface MorphoServiceController {
  supplyErc20(
    request: SupplyERC20Request,
  ): Promise<SupplyERC20Response> | Observable<SupplyERC20Response> | SupplyERC20Response;

  withdrawErc20(
    request: WithdrawERC20Request,
  ): Promise<WithdrawERC20Response> | Observable<WithdrawERC20Response> | WithdrawERC20Response;

  getApr(request: GetAPRRequest): Promise<GetAPRResponse> | Observable<GetAPRResponse> | GetAPRResponse;

  getApy(request: GetAPYRequest): Promise<GetAPYResponse> | Observable<GetAPYResponse> | GetAPYResponse;

  getTvl(request: GetTVLRequest): Promise<GetTVLResponse> | Observable<GetTVLResponse> | GetTVLResponse;

  getLiquidity(
    request: GetLiquidityRequest,
  ): Promise<GetLiquidityResponse> | Observable<GetLiquidityResponse> | GetLiquidityResponse;

  getSuppliedBalance(
    request: SuppliedBalanceRequest,
  ): Promise<SuppliedBalanceResponse> | Observable<SuppliedBalanceResponse> | SuppliedBalanceResponse;

  getLendingPool(
    request: GetLendingPoolRequest,
  ): Promise<GetLendingPoolResponse> | Observable<GetLendingPoolResponse> | GetLendingPoolResponse;
}

export function MorphoServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "supplyErc20",
      "withdrawErc20",
      "getApr",
      "getApy",
      "getTvl",
      "getLiquidity",
      "getSuppliedBalance",
      "getLendingPool",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("MorphoService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("MorphoService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const MORPHO_SERVICE_NAME = "MorphoService";
