// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: strategyActivity/models/getActivity.proto

/* eslint-disable */
import { Any } from "../../google/protobuf/any";

export const protobufPackage = "strategyActivity";

/**
 * {
 *     "walletAddress": "0xC0fcFAd6a5db86F566102B8a7115823068a93c50",
 *     "strategyId": "68c101d5e04b20290589e75f",
 *     "stepId": "",
 *     "action": "deposit",
 *     "title": "deposit 200USDC",
 *     "status": "success",
 *     "data": {
 *         "poolAddress": "0xb125E6687d4313864e53df431d5425969c15Eb2F",
 *         "assetAddress": "0x833589fCD6eDb6E08f4c7C32D4f71b54bdA02913"
 *     }
 * }
 */
export interface Activity {
  walletAddress: string;
  strategyId: string;
  stepId: string;
  action: string;
  title: string;
  status: string;
  data: Any | undefined;
}

export interface GetActivityRequest {
  page: number;
  pageSize: number;
}

export interface GetActivityResponse {
  activities: Activity[];
  total: number;
}

export const STRATEGY_ACTIVITY_PACKAGE_NAME = "strategyActivity";
