// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: strategyActivity/models/submitActivity.proto

/* eslint-disable */
import { Activity } from "./getActivity";

export const protobufPackage = "strategyActivity";

export interface SubmitActivityRequest {
  activity: Activity | undefined;
}

export interface SubmitActivityResponse {
  msg: string;
}

export const STRATEGY_ACTIVITY_PACKAGE_NAME = "strategyActivity";
