// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: protocol/models/getAPR.proto

/* eslint-disable */

export const protobufPackage = "protocol";

export interface GetAPRRequest {
  tokenAddress: string;
  poolAddress: string;
  chainId: number;
}

export interface GetAPRResponse {
  supplyAPR: string;
  borrowAPR: string;
}

export const PROTOCOL_PACKAGE_NAME = "protocol";
