// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: protocol/models/getAPR.proto

/* eslint-disable */

export const protobufPackage = "protocol";

export interface GetAPRRequest {
  tokenAddress: string;
  poolAddress: string;
  chainId: number;
  protocol: string;
}

export interface GetAPRResponse {
  supplyAPR: string;
  borrowAPR: string;
}

export interface GetAPRUniswapv3Request {
  tokenAddress: string;
  poolAddress: string;
  chainId: number;
  protocol: string;
  upperTick: number;
  lowerTick: number;
}

export interface GetAPRUniswapv3Response {
  apr: string;
  feeGrowthGlobal0Now: string;
  feeGrowthGlobal1Now: string;
  feeGrowthGlobal0Past: string;
  feeGrowthGlobal1Past: string;
  feeOutside0LowerNow: string;
  feeOutside1LowerNow: string;
  feeOutside0UpperNow: string;
  feeOutside1UpperNow: string;
  feeOutside0LowerPast: string;
  feeOutside1LowerPast: string;
  feeOutside0UpperPast: string;
  feeOutside1UpperPast: string;
  tickNow: string;
  tickSpacing: string;
  FeeTier: string;
}

export const PROTOCOL_PACKAGE_NAME = "protocol";
