// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: protocol/models/getLTV.proto

/* eslint-disable */

export const protobufPackage = "protocol";

export interface GetLTVRequest {
  tokenAddress: string;
  poolAddress: string;
  chainId: number;
  protocol: string;
}

export interface GetLTVResponse {
  LTV: number;
}

export const PROTOCOL_PACKAGE_NAME = "protocol";
