// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: protocol/models/getSupplyLiquidityUniswapv3Balance.proto

/* eslint-disable */

export const protobufPackage = "protocol";

export interface GetSupplyLiquidityUniswapv3BalanceRequest {
  poolAddress: string;
  userAddress: string;
  chainId: number;
  protocol: string;
}

export interface GetSupplyLiquidityUniswapv3BalanceResponse {
  token0Address: string;
  token1Address: string;
  token0Amount: string;
  token1Amount: string;
  token0Decimals: number;
  token1Decimals: number;
}

export const PROTOCOL_PACKAGE_NAME = "protocol";
