// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.33.0
// source: protocol/models/getSupplyCap.proto

/* eslint-disable */

export const protobufPackage = "protocol";

export interface GetSupplyCapRequest {
  tokenAddress: string;
  poolAddress: string;
  chainId: number;
  protocol: string;
}

export interface GetSupplyCapResponse {
  SupplyCap: number;
}

export const PROTOCOL_PACKAGE_NAME = "protocol";
