// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: protocol/models/withdrawERC20.proto

/* eslint-disable */

export const protobufPackage = "protocol";

export interface BorrowedBalanceRequest {
  userAddress: string;
  /** supplied token address */
  tokenAddress: string;
  ChainID: number;
  poolAddress: string;
}

export interface BorrowedBalanceResponse {
  tokenAddress: string;
  balance: string;
  decimals: string;
}

export const PROTOCOL_PACKAGE_NAME = "protocol";
