// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.7
//   protoc               v6.32.1
// source: hypurrfi/models/supplyERC20.proto

/* eslint-disable */

export const protobufPackage = "hypurrfi";

export interface SupplyERC20Request {
  userAddress: string;
  orchestratorAddress: string;
  strategyId: string;
  poolAddress: string;
  amount: string;
  assetAddress: string;
  permissionId: string;
}

export interface SupplyERC20Response {
  chainId: number;
  txHash: string;
  amount: string;
  superTxHash: string;
}

export const HYPURRFI_PACKAGE_NAME = "hypurrfi";
